### ISSUE TITLE
Crashes every time I launch the game / game is open

### ISSUE THREAD

**Issue by hjbdev** [osztenkurden/CS-GO-Observer-Custom-HUD#1]
debug.log from NW:

[0831/181148.186:WARNING:chrome_main_delegate.cc(590)] final extension: 

HUD Opens and then closes instantly :(

**Comment by sinistersnare** [comment]
In your `package.json` can you change `"chromium-args"` to this?

` "chromium-args": "--disable-gpu --force-cpu-draw --enable-logging=stderr"`


what does console output now?

**Comment by hjbdev** [comment]
there isn't anything in cmd, and the debug.log just contains the same error

**Comment by hjbdev** [comment]
MY BAD!
