### ISSUE TITLE
Dont know how to start

### ISSUE THREAD

**Issue by ghost** [osztenkurden/CS-GO-Observer-Custom-HUD#11]
I really don't know how to start with it

**Comment by vtumialan** [comment]
https://github.com/osztenkurden/CS-GO-Observer-Custom-HUD#how-i-made-it-run

**Comment by ghost** [comment]
Yeah, but i did all from it, but it don't synchronize with game info

**Comment by vtumialan** [comment]
Try this https://github.com/sinistersnare/CS-GO-Observer-Custom-HUD

**Comment by ghost** [comment]
Thanks! Now it works. I have one more question. Can i scale it in any way?

**Comment by vtumialan** [comment]
I think so, I saw that the whole design is html / css. Easily modifiable
