### ISSUE TITLE
Change font and size text

### ISSUE THREAD

**Issue by benten2411** [osztenkurden/CS-GO-Observer-Custom-HUD#13]
Someone can help me to change font and size text. This project is awesome

**Comment by sinistersnare** [comment]
All of that is in the HTML, so youre gonna want to change the appropriate CSS.

**Comment by benten2411** [comment]
ik but which file? do u know it?

**Comment by sinistersnare** [comment]
style.css is the css file to edit.

**Comment by elpides** [comment]
Please sinistersnare, which line changes font of the players name?
I'm confused

**Comment by sinistersnare** [comment]
players name is in `#current_nick` if I remember correctly, so the CSS would be something like:

```css
#current_nick {
    font-family: "Times New Roman", Times, serif;
}
```

You can use any font installed on your system, and it is case-sensitive. Hope it works out for ya.

**Comment by elpides** [comment]
sinisternare plz help me again? 
And how do I put a flag of each country of the players. (a time mix countries)

add me plz? steamcommunity.com/id/pidimbr
thx dude

**Comment by sinistersnare** [comment]
Team flags are in `#team_1 > #team_logo > #team_flag` (or `#team_2` for team 2). You can use the server.js file to edit them dynamically.

I am not interested in helping you learn to use HTML/CSS/JS, sorry.

**Comment by elpides** [comment]
thx sinisternare

**Comment by sinistersnare** [comment]
I have a fork of this which is a bit easier to use IMO: https://github.com/sinistersnare/CS-GO-Observer-Custom-HUD

**Comment by elpides** [comment]
I'm starting to learn. But I still have these things to change.
Your conf: http://i66.tinypic.com/2450951.jpg
My conf: http://i64.tinypic.com/289yb6d.jpg

I have a problem the moment FLASH popped ... and
Idk how to put the KAD bar after the nick... and 
other more ... lul :P
very thx my man

**Comment by elpides** [comment]
sinisternare Last help please ...
http://ap.imagensbrasil.org/image/nFVgo6
Thx!!

**Comment by sinistersnare** [comment]
Sorry, I am not interested in helping right now. Maybe find someone you know IRL with web-development experience, they should be able to help.

**Comment by elpides** [comment]
ok thx!
