### ISSUE TITLE
Help me !

### ISSUE THREAD

**Issue by MgWish** [osztenkurden/CS-GO-Observer-Custom-HUD#14]
sir plz help me Step by Step video :D i want
i Fail ur script .... 
very headcache !_!
i test 3 day this one !

becoz i'm organizer of mm league 
i want to use ur hub in my league
ty sir

**Comment by sinistersnare** [comment]
Ill make a video of how to use it for money.

**Comment by vtumialan** [comment]
You must verify that you have correctly installed node.js and nw.js. The files must be in the correct folders and that's it.

**Comment by vtumialan** [comment]
Try the new version that went up
