### ISSUE TITLE
No utility images

### ISSUE THREAD

**Issue by 8vantar** [osztenkurden/CS-GO-Observer-Custom-HUD#15]
Everything works but the icons for utility (armor, nades, etc)

**Comment by sinistersnare** [comment]
Did you fix the issue? Please comment on what you did in case anyone has this issue again.

**Comment by 8vantar** [comment]
Drag n' Dropping the contents of [pgl example hud (3).zip](https://mega.nz/#!z1BFmSLK!-flNUrbjuvhDAPkPgmh0wzgDpmJqgkoC-AlrY9ngPH8) into the "server" folder fixed the issue
