### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by ghost** [osztenkurden/CS-GO-Observer-Custom-HUD#17]
Hello.

Problem with flags, whenever I make a team, the player flags won't apply, like I want to have a danish player but if the team flag is EU for instance it will make all player flags EU.

TLDR: Player flags are ignored, and it will just display team flag instead.

If you could help me out oszten to fix that issue it would be really helpful.

Thanks !

**Comment by dayike** [comment]
Also the Ammunition (like 19/20 bullets) are slightly misaligned.

If you could help me out oszten to fix those 2 issues it would be really helpful.

Thanks !
