### ISSUE TITLE
EXE not working

### ISSUE THREAD

**Issue by r0ggerz** [osztenkurden/CS-GO-Observer-Custom-HUD#22]
so ib ahve set everything up is in the video and the README, using port 2144, but when i run the exe it opens for 1 second then closes it self. no idea why. i really need this for my new casting deal

**Comment by mahcyen** [comment]
try creating a config.json file with the same folder as the exe

**Comment by r0ggerz** [comment]
cheers dude :)

>

**Comment by GenaroTerron** [comment]
Excuse me for reopen this issue, i´m new with all this stuff and dont understand this solution "try creating a config.json file with the same folder as the exe", can anybody explain me with more detail please?
