### ISSUE TITLE
too many server commands issued per second

### ISSUE THREAD

**Issue by godizord** [osztenkurden/CS-GO-Observer-Custom-HUD#24]
when executing exec gamestate_integration_observerspectator.cfg it prompt me this issue, is there a new version of that file? where can I get it?

Ignoring command '   "player_state"        "1"      ': too many server commands issued per second
Ignoring command '   "allplayers_state"    "1"      ': too many server commands issued per second
Ignoring command '   "allplayers_match_stats"  "1"  ': too many server commands issued per second
Ignoring command '   "allplayers_weapons"  "1"      ': too many server commands issued per second
Ignoring command '   "allplayers_position" "1"     ': too many server commands issued per second
Ignoring command '   "phase_countdowns"    "1"    ': too many server commands issued per second
Ignoring command ' }': too many server commands issued per second
Ignoring command '}': too many server commands issued per second

![image](https://user-images.githubusercontent.com/5333436/43319519-14af28d4-9173-11e8-9e84-72d35cd70ae1.png)

Thanks in advance

**Comment by JesusWithPants** [comment]
You dont need to exec the gamestate_integration_observerspectator.cfg. Just put it in csgo/cfg folder, restart game and forget about it...

**Comment by godizord** [comment]
Done, thanks @JesusWithPants
