### ISSUE TITLE
New Game State Integration field, how to use?

### ISSUE THREAD

**Issue by LukasW1337** [osztenkurden/CS-GO-Observer-Custom-HUD#25]
The newest update to CSGO included this change:

- Game state integration includes a field “round_totaldmg” to track total damage the player dealt.

Does this need an update to the source code to use? or is it just available by default now?

**Comment by stormonster** [comment]
This is implemented and you can work with it already.
    
    console.log(teams.left.players[0].state.round_totaldmg);

**Comment by realS3BI** [comment]
> The newest update to CSGO included this change:
> 
> * Game state integration includes a field “round_totaldmg” to track total damage the player dealt.
> 
> Does this need an update to the source code to use? or is it just available by default now?

Where should i put it in my .js file? or how can i implement in my .pug file?

**Comment by LukasW1337** [comment]
@007sebi007 you use it in javascript - and @stormonster gave a great example of how to use it
