### ISSUE TITLE
Overtime FIX

### ISSUE THREAD

**Issue by glockmaster** [osztenkurden/CS-GO-Observer-Custom-HUD#27]
Hi,

Is there any chance to make overtime on the top bar?

**Comment by myrzagali** [comment]
if ( map.round >= 30) {
         if ( ((map.round + 6) % 6) < 6) {
             $("#round_counter").html("Round " + round_now + " / " + ( (map.round + 6) - ((map.round + 6) % 6) ));
         }
    }
    else {
        round_now ? $("#round_counter").html("Round " + round_now + " / 30") : $("#round_counter").html("Round 0 / 30");
    }
