### ISSUE TITLE
Using CasparCG instead of Overlay exe

### ISSUE THREAD

**Issue by Sega01** [osztenkurden/CS-GO-Observer-Custom-HUD#28]
Hi,

I dont know if you are familar with the tool called "CasparCG". I want to use that for laying the live stats over the game. I have the following setup:
- One Game PC, where CS:GO is running
- One PC with the CasparCG Server on it, which is just sending the signal
- One PC with the CasparCG Client, where the Node.js server is running.

Now I get all data on the client from the CS:GO pc and Im able to show the tab in the CasparCG window with the HTML template. The only problem is, that all values are basic and not dynamic. Any idea how I could fix it?

**Comment by JesusWithPants** [comment]
Define basic?

**Comment by Sega01** [comment]
All standard values for example all health bars on 100, bomb timer on max time. 
You could say it shows the basic html without execute the script or hide any elements. I hope this was better understandable 

edit: In the browser everything works. Just if I load the page with the load html function into the CasparCG tool I just see the things, that i mention above.

edit2: I cant check that right now, but Im pretty sure in the logs of CasparCG was something like "Unexpected Syntax" in a .js file. Tho it worked in the browser perfectly.

**Comment by pz1k** [comment]
I believe he meant STATIC, not basic.

**Comment by Everton747** [comment]
I didn't unsderstand. Do you want to put the entire hud in casparCG? or just display some statistics? I recommend you create a server socket from statistics to CasparCG template.

**Comment by Sega01** [comment]
Yea I wanted to show the hud in CasparCG and I found my fault.... Well lets not talk about it. I used a version that was using a browser that was waaaaaaay too old to handle the javascript. After using the newest version no problem to use the hud in CasparCG as a html page.

**Comment by Everton747** [comment]
The CasparCG uses very old chromium versions. Only 2.2.0 (stable version) solve that. One tip, i like to use NRK-Server version. https://github.com/nrkno/tv-automation-casparcg-server/releases

**Comment by Sega01** [comment]
Yes, Im using the 2.2.0 version right now. 
Thank you for the tipp: I will look for that version if I get some spare time!

edit: Is there any recommend client besides the normal one? I saw that there are a few on github too

**Comment by Everton747** [comment]
Exists a lot of clients. Depends of your necessity. If you use only to launch CS:GO HUD, the default client is the best.

**Comment by Sega01** [comment]
Mainly it would be used for different kind of games, not only the CS:GO HUD or different graphics/overlays like lower third things etc

**Comment by Everton747** [comment]
I think that default client is perfect for lower thirds, graphics and overlays. Most clients are created for automation, or for specific things (ex. Sports scoreboard, Replays). I think you can try to create to yourself. I am creating my own using JavaScript and Electron. There is already a library that communicates with the Caspar server, so it's easy to do.

https://github.com/CasparCG/help/wiki/List-of-clients-for-controlling-CasparCG

**Comment by Sega01** [comment]
For now with the NRK-customized server and the official client I have all things I need for now. I planned to look into that when I have some spare time, now its full stress :D I would work with node/react and/or electron for that. 
My current problem is more that I need to read out the opacity value of a layer through JustMacros, but this is much offtopic here
