### ISSUE TITLE
Default Hud - always displaying avatars

### ISSUE THREAD

**Issue by Ejay2287** [osztenkurden/CS-GO-Observer-Custom-HUD#38]
Hey, I'm having a problem with the player information in the bottom middle it is always showing avatars. I go into config.json and change 'DisplayAvatars' from 'false' to 'true' and put in a 'SteamApiKey' and it shows perfectly centred with avatar but when 'DisplayAvatars' is set to 'false' the player information is still in the same place as if the avatar was there and when you have the SteamApiKey setup it shows avatars regardless of DisplayAvatars.

TLTR: The program isn't reading DisplayAvatars correctly and is always displaying for avatars

**Comment by pablo311** [comment]
Hi. how are you? tell me I have a problem with the csgo hud installation could you help me?

**Comment by Ejay2287** [comment]
@pablo311 Yeah sure, here is a video of me going over the installation process (without a script) It's a little messy but it goes over everything you need to do to get it working and a little bit more. https://www.youtube.com/watch?v=qZx0Qf6pbnI

**Comment by Athar42** [comment]
@Ejay2287 Reason is there, this my comment : https://github.com/osztenkurden/CS-GO-Observer-Custom-HUD/commit/1298c89c824e931ecd5beaf561fa818157eb2282#r33970672

**Comment by Ejay2287** [comment]
That is ummm really stupid. Thanks for bringing that up. @osztenkurden please fix <3
