### ISSUE TITLE
Setting images and team logos

### ISSUE THREAD

**Issue by Cooopster** [osztenkurden/CS-GO-Observer-Custom-HUD#39]
Hey all, just having some struggles trying to set profile pictures to certain steam id's and can't manage to get Team logos on player containers.

**Comment by Ejay2287** [comment]
You can set team logos in the 'Teams' section of the server web page thing

If you want to change profile pictures of a player different from their existing profile pictures, you have to go into public/files/avatars This folder holds all the profile pictures and each profile picture is named according to the players steamID. So you can just grab the picture you want and name it the steamID of the player you want to change

**Comment by Cooopster** [comment]
Thanks for the help with avatars. But do you the remember the pgl and eleague major where the team logos were in the first row/player container? So i can have both player flag and team logos

**Comment by Ejay2287** [comment]
![this](https://user-images.githubusercontent.com/26950406/61167300-2a902f00-a580-11e9-9379-69b0e566cfba.PNG)
Do you mean having the player's flag there? And having the logo behind the name cut off

**Comment by Cooopster** [comment]
Do you see the faint logo behind it? At the moment its not part of the player container and was wondering how

**Comment by Ejay2287** [comment]
I'm still learning CSS and mucking around with variables and adding new stuff. So I don't have much of a clue of how to do that myself sorry. I would recommend experimenting and just trial and error.

**Comment by Cooopster** [comment]
I think I have it down im just having troubles getting the logos to switch between the t sides and ct sides

**Comment by Ejay2287** [comment]
Yeah, I would say that would be handled by the JS. maybe see if you can get it to change based on the player container colour

**Comment by Cooopster** [comment]
It is in the JS however i have tried multiple times with different combinations of a players team and to no success. Makes you wonder sometimes how this guy made it xD. Also would you know anything about gradients on the hp bars?

**Comment by Ejay2287** [comment]
Yeah XD, I've got no idea about the health bars sorry.

**Comment by Cooopster** [comment]
All good, thanks for the hep!
