### ISSUE TITLE
NPM can't find the files in system32 folder.

### ISSUE THREAD

**Issue by ghost** [osztenkurden/CS-GO-Observer-Custom-HUD#40]
The error I get:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
5 verbose cwd C:\WINDOWS\system32
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v10.16.0
9 verbose npm  v6.9.0
10 error path C:\WINDOWS\system32\package.json
11 error code ENOENT
12 error errno -4058
13 error syscall open
14 error enoent ENOENT: no such file or directory, open 'C:\WINDOWS\system32\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]
`

**Comment by Ejay2287** [comment]
Not really sure what's happening here but I had a little trouble with NPM and had to type 'npm update' into cmd. Else I would reinstall node JS, restart the pc, But it might also be unable to locate 'package.json' from this "ENOENT: no such file or directory" Looking around I found this on StackOverflow: https://stackoverflow.com/questions/9484829/npm-cant-find-package-json and it says to try 'npm init' not sure if that will create the windows package but worth a try. Good Luck
