### ISSUE TITLE
Gradient hp bar isn't working

### ISSUE THREAD

**Issue by Cooopster** [osztenkurden/CS-GO-Observer-Custom-HUD#41]
When I try making a hp gradient bar the health doesn't go down and at the end of the round isn't refreshed. Assuming it's something to do with the JS
![rip](https://user-images.githubusercontent.com/47094986/61214259-ca011d80-a74a-11e9-87f8-b796565ca751.PNG)

**Comment by RAKW** [comment]
You need to change the gradient in the index.js of your hud, not the css.
I do it like this:

`  let health_gradient_left = statistics.health <= 20 ? "#ff0000" : team == "ct" ? "#00a0ff":"#ffa000";
    let health_gradient_right = statistics.health <= 20 ? "#ff0000" : team == "ct" ? "#F939E3":"#F939E3";
    let $player = $("#"+side).find("#player"+(nr+1));

    let $bottom = $player.find(".bottom_bar");
    let $top = $player.find(".bar1");



    //let gradient = "linear-gradient(to " + side +", rgba(0,0,0,0) " + (100-statistics.health) + "%, " + health_color + " " + (100-statistics.health) + "%)";
    let gradient = "linear-gradient(to " + side +", rgba(0,0,0,0) " + (100-statistics.health) + "%, " + health_gradient_left + " " + (100-statistics.health) + "%, " + health_gradient_right + " 100%)";`
