### ISSUE TITLE
"found 3 high severity vulnerabilities" when starting via .bat file

### ISSUE THREAD

**Issue by RAKW** [osztenkurden/CS-GO-Observer-Custom-HUD#42]
When running the .bat file node tells me there are "high severity vulnerabilities". Basically it comes from using old versions of socket.io and lodash. I set the socket.io version to "latest" in the package.json and it seems to work fine still but I'm pretty clueless about lodash. Now I know this is supposed to run locally and stuff but still it would be nice to not get these messages.

**Comment by AkalaAkala** [comment]
Says 9 for me. "8 low, 1 high"

**Comment by ndstudios-admin** [comment]
> When running the .bat file node tells me there are "high severity vulnerabilities". Basically it comes from using old versions of socket.io and lodash. I set the socket.io version to "latest" in the package.json and it seems to work fine still but I'm pretty clueless about lodash. Now I know this is supposed to run locally and stuff but still it would be nice to not get these messages.

Hey! I set it to latest as you did but it didn't work for me. It just said that found 0 vulnerabilities and crashes
