### ISSUE TITLE
Dont start up

### ISSUE THREAD

**Issue by maver1ckgg** [osztenkurden/CS-GO-Observer-Custom-HUD#46]
Hi Guys, 

i did everything like in the setup video and doesnt matter if I stay on the default config or take the vesper2. When i open the console and load the "observer" all overlay is gone. The Standard and the OBServer ones. 
I copied all configs,using csgo in Fullscreen Windowed. 
Can you please help me?

Thanks Guys

**Comment by Ejay2287** [comment]
Hey @maver1ckgg try running through the setup again with my video https://www.youtube.com/watch?v=qZx0Qf6pbnI if you still have problems, let me know.
