### ISSUE TITLE
"Found 0 vulnerabilities" and crash (run.bat file)

### ISSUE THREAD

**Issue by ndstudios-admin** [osztenkurden/CS-GO-Observer-Custom-HUD#49]
The RUN file don't give me an IP address. It crashes all the time. In package.json I "socket.io" to latest but it also didn't work

**Comment by Salty-Jayy** [comment]
In the config.json file and the gamestate_integration_observerspectator.cfg file change the GameStateIntegrationPort from 1337 to 1338.

That worked for me. Hope it helps you :)

glhf
@Salty_Jayy
