### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by N0N-afk** [osztenkurden/CS-GO-Observer-Custom-HUD#50]
I get this error message when I ran the RUN.bat file in cmd and when I try to run it regularly it runs and then does not give me the IP and the closes.
![7d9ec310136e59082999906911855069](https://user-images.githubusercontent.com/59351910/71759536-60053d80-2e7c-11ea-8442-a3ebd7157111.png)

**Comment by jamesql** [comment]
send a screenshot of your ./ folder (master folder)
and the code in your bat

**Comment by N0N-afk** [comment]
![9e9ee391500388dc4aa72d860c5cb5f0](https://user-images.githubusercontent.com/59351910/71774581-c8692300-2f3f-11ea-8f0c-0fba7c316a36.png)
That is what was in the bat file once I went to edit it (I didn't change anything in the notepad). I also don't know how to find the master folder, still kind of new to much of this stuff.

**Comment by jamesql** [comment]
Your batch file is not looking in the right dir for the index
its looking in C:/Users/% when it should be looking in the master folder.
the file could not be in the right folder or you need to cd to the path
