### ISSUE TITLE
Add support for ADR

### ISSUE THREAD

**Issue by Barsnes** [osztenkurden/CS-GO-Observer-Custom-HUD#51]
I saw in an earlier issue that ADR is not supported in the current version because you don't get it form the game data.

Well, since you are getting  `round_totaldmg`, you can easily add this to a variable `match_totaldmg` and then simply do `match_totaldmg / map.round` to get the ADR. 

I hope you will add this as a native variable to `player.match_stats`

**Comment by Sharken03** [comment]
Note that there is no cumulative value for player damage, so if you restart the overlay or join a match after a few rounds, you won't be able to get the correct ADR value.
The Game State Integration data needs a field such as `match_totaldmg` to prevent that from happening.

**Comment by andura321** [comment]
@Barsnes Can you learn me how?, I need it </3

**Comment by Barsnes** [comment]
@andura321 As mentioned above, `match_totaldmg` would be reset if you refresh the hud, or would be wrong if you joined late/dropped from the server. Only way to "fix" this is to have a bot on the server that gathers more data than GameState, and sends it to your hud for you to use.

You can do what i proposed in my original post, but there would be the possibility for a lot of bugs and flaws.

**Comment by Sharken03** [comment]
I actually wrote to csgoteamfeedback@valvesoftware.com to ask for a `match_totaldmg` field if you joined a game late, but did not yet get a response from Valve. Ideally it should also offer the historic values, right now you can only do as @Barsnes suggest.
