### ISSUE TITLE
About Flashes

### ISSUE THREAD

**Issue by EmirBoyaci** [osztenkurden/CS-GO-Observer-Custom-HUD#55]
Hello,
In /public/flases folder we have flashbang images, I saw these images in ESL csgo broadcasts. We have that images but there is no code for adding these images when someone blind. Can someone explain to me how can I add these flashbang images properly?

Thanks.

Edited: @osztenkurden can you explain please :)

**Comment by AndreasZacchi** [comment]
Hello, to implement the 31 flash images you'll have to change the code here 
```javascript
if (stats.flashed > 0 && !dead) {
    $player.find(".flashed").css("display", "block");
    $player.find("#flashed_level").addClass("blind");
    $player.find("#flashed_level").css("opacity", stats.flashed / 255);
  }
```
This is where it makes the current flashed image (icon_blind.png) opacity change according to the flashed amount, you'll have to implement this functionality yourself by changing the image according to the `stats.flashed` variable.
