### ISSUE TITLE
RUN crashed

### ISSUE THREAD

**Issue by BeiranZz** [osztenkurden/CS-GO-Observer-Custom-HUD#56]
I ran my RUN file, 5 seconds later it closes.
Need help

**Comment by AndreasZacchi** [comment]
Hello can you be a bit more specific, does it output anything in the console? Do you have node.js installed etc.

**Comment by BeiranZz** [comment]
> Hello can you be a bit more specific, does it output anything in the console? Do you have node.js installed etc.

Hey,
I installed the hud on 2 computers. On my laptop it worked but on my main computer it didn't work, and I did exacly the same thing. I have node.js installed. The problem is when I run my Run file it starts doing something and ouputing everything but when it is suposed to output the link, the run crashes, it closes.

**Comment by AndreasZacchi** [comment]
Is #57 similar to your problem?

**Comment by BeiranZz** [comment]
> Is #57 similar to your problem?

Yeh, it's the same problem.

**Comment by AndreasZacchi** [comment]
Are you running the same node version on both PC's?
`node -v`

**Comment by BeiranZz** [comment]
Yes

**Comment by AndreasZacchi** [comment]
What happens if you open a cmd in the folder of the run.bat and type `node index.js` if it runs then there is a problem with npm

**Comment by Salty-Jayy** [comment]
In the config.json file and the gamestate_integration_observerspectator.cfg file change the GameStateIntegrationPort from 1337 to 1338.

That worked for me. Hope it helps you :)

glhf
@Salty_Jayy

**Comment by BeiranZz** [comment]
Thank you, it worked.
Anyway knows why the OVERLAY DOWNLOAD link is not working?

**Comment by AndreasZacchi** [comment]
Check #58 for a 64 bit version.
