### ISSUE TITLE
 OVERLAY DOWNLOAD cannot be downloaded.

### ISSUE THREAD

**Issue by misiu29** [osztenkurden/CS-GO-Observer-Custom-HUD#58]
“Please make sure the URL is correct and the file does exist.”

**Comment by AndreasZacchi** [comment]
The link is down, I have uploaded the 64 bit version [here](https://drive.google.com/file/d/1FxtMcrYERUiwY4HT_RZNmjhc8OYEd_Xh/view?usp=sharing) for free use. Sadly if you're on a 32 bit machine you're most likely out of luck unless somone else can provide it.

**Comment by misiu29** [comment]
I am a 64-bit system, thank you very much! And I found that it can be used directly without exe. Thank you anyway! (Sorry for my bad English.)
