### ISSUE TITLE
How to change xray color?

### ISSUE THREAD

**Issue by joxgarcia1997** [osztenkurden/CS-GO-Observer-Custom-HUD#59]
I know  that this is not an issue on the hud, the hud its pretty nice (but i think that needs some improvemnts to resolve the dependencies when we run the batch)

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

Another thing, i recently notice some tournaments that they change the xray color. Ill leave some links of examples. 

Can some one tell me how to change the color? 

https://www.twitch.tv/temporadadejuegos/clip/CharmingBlazingKoupreyWow?filter=clips&range=7d&sort=time

Here they use red/la better blue
or  this one 
https://www.twitch.tv/gridesports/clip/GeniusStrangeSpiderSSSsss?filter=clips&range=7d&sort=time

Also, like the blastPremier, change also the deathnotice letters. 

pls help?

**Comment by MonsieurBibo** [comment]
I think you need to use AdvanceFx w/ this link to help https://github.com/advancedfx/advancedfx/wiki/CS%3AGO-Changing-X-Ray-color
