### ISSUE TITLE
Observed Player

### ISSUE THREAD

**Issue by realS3BI** [osztenkurden/CS-GO-Observer-Custom-HUD#60]
Hey guys!

CAn somebody say me, how i can the information, which player is currently observed in the team bars on the side.

See this example by ESL:

<img width="1291" alt="ESL Observed" src="https://user-images.githubusercontent.com/62571444/83663840-7d743a00-a5c9-11ea-9624-db23ce1a147d.png">

Thx for your answers!

**Comment by MonsieurBibo** [comment]
hey, I'm not working at ESL, but they probably have a database with all players in their competition.
They're also probably running CS:GO in windowed mode and the developer behind it just need to create some "if" for each player. It takes his data from the db and display it on screen.
