### ISSUE TITLE
Cant Remove Viewers / Drop from layout and other funcs

### ISSUE THREAD

**Issue by glockmaster** [osztenkurden/CS-GO-Observer-Custom-HUD#8]
Hi,

I cant remove the top right tab of the layout that contains viewers and drops  wich i want to. Im trying to add the functionality like the bar when defusing or planting, adding the avatar of steam on the player bar instead of flag and the timeouts remaining var timeouts_t = team.timeouts_remaining that isnt working.

If any of you can tell me what i should write for code, i appreciate.
Happy New Year

**Comment by FlowingSPDG** [comment]
Edit huds/Example_HUD_PGL/index.html
Remove line 38~41 to delete them.
I don't know about defuse bars but...goodluck m8 👍

**Comment by glockmaster** [comment]
Ive been looking at some nice projects on github and writing into paper all of the stuff to try to learn this. But Thanks mate

**Comment by vtumialan** [comment]
Hi guys, i cant make it work, as u do to update the view.
