### ISSUE TITLE
Win team message and defuse animation - Need Help

### ISSUE THREAD

**Issue by glockmaster** [osztenkurden/CS-GO-Observer-Custom-HUD#9]
Hi all

Im trying to add something new since i dont program since more then 6+ years. I want to know how i can program the messages of the winning team + defuse timer to appear on the screen.

Best Regards

**Comment by elpides** [comment]
me too need help

**Comment by vtumialan** [comment]
I was going to add that option but i haven't had time lately, when i finish it i share it here.

**Comment by elpides** [comment]
Thx vtumialan! :D

**Comment by gitShan** [comment]
Somebody has an solution?

**Comment by vtumialan** [comment]
Team win:
server.js
```
    if(round.phase == "over") {
      if(round.win_team == 'CT' && data.info.map.round < 16) {
          /*Text or Event when CT wins to the left*/
      }
      if(round.win_team == 'CT' && data.info.map.round > 15) {
          /*Text or Event when CT wins to the right*/
      }
      if(round.win_team == 'T' && data.info.map.round < 16) {
          /*Text or Event when T wins to the left*/
      }
      if(round.win_team == 'T' && data.info.map.round > 15) {
          /*Text or Event when CT wins to the right*/
      }
    } else {
        Revert or hide text/alert
    }

```
Defuse animation:
```
        if (phase.phase == "defuse") {
            /* While defusing the c4 */
        }
```

**Comment by clovermye** [comment]
Hi @vtumialan 
The only file "server.js" that I found in ""CS-GO-Observer-Custom-HUD-master\node_modules\engine.io\lib" and when I paste the code and open the panel doesn't work.
Please help!

**Comment by stormonster** [comment]
Something along these lines in the "index.js" of the HUD you are working on should do it for round wins.
This of course requires that you have a div-element in the .pug file with the id of "who_won". I would recommend setting the opacity of "#who_won" in the css file to 0 by default too.

    if (phase.phase == "over") {
    let winningTeamName = null;
    winTeam = (round.win_team.toLowerCase() == 't' ? team_t : team_ct);
    round.win_team.toLowerCase() == teams.left.side.toLowerCase() ? winningTeamName = teams.left.name : winningTeamName = teams.right.name;
    
    $('#who_won').html('<p><span class="' + round.win_team.toLowerCase() + '-color" style="display: inline-block; margin: 0;">' + winningTeamName + '</span> wins the round!</p>');

    if (phase.phase_ends_in > 1) {
        if ($("#who_won").css("opacity") == 0) {
            $("#who_won").fadeTo(1000, 1);
        }
    } else {
        if ($("#who_won").css("opacity") == 1) {
            $("#who_won").fadeTo(1000, 0);
        }
    }
    } else {
    if ($("#who_won").css("opacity") == 1) {
        $("#who_won").fadeTo(1000, 0);
    }
    }
    var winTeam = null;
